window.MOCK_QUESTIONS = {
  iq: [
    { q: "ما هو الرقم التالي في المتسلسلة: 2, 4, 8, 16, ...؟", options: ["20", "24", "32", "64"], correct: 2 },
    { q: "إذا كان 'الأسد' للـ 'عرين'، فإن 'النحل' للـ ...؟", options: ["الخلية", "العش", "الحظيرة", "الجحر"], correct: 0 },
    { q: "ما هو الحرف التالي في المتسلسلة: أ، ت، ج، خ، ...؟ (باستثناء النقط)", options: ["د", "ذ", "ر", "ز"], correct: 0 },
    { q: "كم عدد المربعات في رقعة الشطرنج؟", options: ["64", "65", "204", "100"], correct: 0 },
    { q: "أوجد الشاذ: تفاحة، برتقالة، بطاطس، موزة", options: ["بطاطس", "موزة", "تفاحة", "برتقالة"], correct: 0 },
    { q: "عمر والد أحمد 3 أضعاف عمر أحمد. بعد 10 سنوات يصبح ضعف عمر أحمد. كم عمر أحمد الآن؟", options: ["5", "10", "15", "20"], correct: 1 },
    { q: "إذا كان أمس هو غداً لليوم الذي قبل الأحد، فما هو اليوم؟", options: ["الأحد", "الاثنين", "الجمعة", "السبت"], correct: 3 },
    { q: "أي الأرقام التالية لا ينتمي: 3، 5، 7، 9، 11", options: ["9", "11", "3", "7"], correct: 0 }, // 9 is not prime
    { q: "قطار يتحرك بسرعة 100 كم/س، ما المسافة التي يقطعها في 45 دقيقة؟", options: ["45", "60", "75", "100"], correct: 2 },
    { q: "مربع طول ضلعه 4، ما هو محيطه؟", options: ["12", "16", "20", "8"], correct: 1 },
    { q: "ما الرقم الذي يجب أن يحل محل علامة الاستفهام؟ 1, 1, 2, 3, 5, 8, ?", options: ["11", "12", "13", "14"], correct: 2 }, // fibonacci
    { q: "شخص اشترى سلعة بـ 100 وباعها بـ 120، ثم اشتراها بـ 130 وباعها بـ 150. كم ربحه الإجمالي؟", options: ["20", "30", "40", "50"], correct: 2 },
    { q: "رتب كلمات (ذهب، إلى، المدرسة، أحمد) لتصبح جملة صحيحة.", options: ["إلى المدرسة ذهب أحمد", "أحمد ذهب إلى المدرسة", "المدرسة إلى ذهب أحمد", "ذهب أحمد المدرسة إلى"], correct: 1 },
    { q: "الكلمة وعكسها، أوجد الخطأ:", options: ["طويل - قصير", "سريع - بطيء", "جميل - قبيح", "غبي - أحمق"], correct: 3 },
    { q: "أي من هذه الأشكال ليس مضلعاً؟", options: ["المثلث", "المربع", "الدائرة", "الخماسي"], correct: 2 },
    { q: "نصف الربع يساوي؟", options: ["خُمس", "ثُمن", "سُدس", "نصف"], correct: 1 },
    { q: "إذا كان محمد أطول من سعيد، وسعيد أطول من علي، فإن محمد...", options: ["أقصر من علي", "أطول من علي", "بنفس طول علي", "لا يمكن التحديد"], correct: 1 },
    { q: "الكتاب للورق مثل البيت للـ...", options: ["الباب", "الطوب", "السقف", "الشباك"], correct: 1 },
    { q: "أكمل المتتالية: 10, 9, 7, 4, ...", options: ["0", "1", "2", "3"], correct: 0 }, // -1, -2, -3, -4
    { q: "3 قطط يصطادون 3 فئران في 3 دقائق، كم قطة تلزم لصيد 100 فأر في 100 دقيقة؟", options: ["100", "3", "33", "10"], correct: 1 },
    { q: "ما العدد الذي ثلثه يساوي 12؟", options: ["15", "24", "36", "48"], correct: 2 },
    { q: "أي الكلمات التالية هي الأقرب في المعنى لكلمة 'شجاع'؟", options: ["ذكي", "مقدام", "سريع", "هادئ"], correct: 1 },
    { q: "ساعة تسبق بمقدار دقيقة كل يوم، كم دقيقة ستسبق بعد أسبوع كامل؟", options: ["6", "7", "14", "1"], correct: 1 },
    { q: "إذا كان 'كلب' = 3، و'حصان' = 4، و'أسد' = 3، فكم يساوي 'فيل'؟", options: ["2", "3", "4", "5"], correct: 1 }, // number of letters
    { q: "الأخضر ينشأ عن خلط...", options: ["الأحمر والأزرق", "الأزرق والأصفر", "الأصفر والأحمر", "الأسود والأبيض"], correct: 1 },
    { q: "مربع داخله دائرة تمسه من الداخل، مساحة المربع...", options: ["أكبر", "أصغر", "تساوي", "ضعف مساحة الدائرة"], correct: 0 },
    { q: "المتر كم سنتيمتر؟", options: ["10", "100", "1000", "10000"], correct: 1 },
    { q: "عكس كلمة 'صواب' هو...", options: ["حقيقة", "خطأ", "جميل", "واضح"], correct: 1 },
    { q: "كم شهراً في السنة يحتوي على 28 يوماً؟", options: ["1", "6", "11", "12"], correct: 3 }, // all months have at least 28 days
    { q: "سلسلة: 2A, 4B, 6C, 8D, ... الاستمرار هو؟", options: ["9E", "10F", "10E", "12E"], correct: 2 }
  ],
  science: [
    { q: "ما هي الجسيمات الموجودة داخل نواة الذرة بشحنة موجبة؟", options: ["الإلكترونات", "البروتونات", "النيوترونات", "الفوتونات"], correct: 1 },
    { q: "ماذا يسمى جهاز قياس الضغط الجوي؟", options: ["الترمومتر", "البارومتر", "الأنيمومتر", "الهيجرومتر"], correct: 1 },
    { q: "أي العناصر الكيميائية التالية رمزه (O)؟", options: ["الذهب", "الأكسجين", "الحديد", "الكربون"], correct: 1 },
    { q: "ما هي العملية التي تقوم بها النباتات لصنع الغذاء؟", options: ["التنفس", "البناء الضوئي", "الاحتراق", "التبخر"], correct: 1 },
    { q: "أي من هذه المعادن ينجذب للمغناطيس؟", options: ["النحاس", "الفضة", "الحديد", "الذهب"], correct: 2 },
    { q: "ما هو العنصر الأكثر وفرة في الغلاف الجوي للأرض؟", options: ["الأكسجين", "النيتروجين", "الهيدروجين", "ثاني أكسيد الكربون"], correct: 1 },
    { q: "كم عدد الكروموسومات في الخلية البشرية العادية؟", options: ["23", "46", "24", "48"], correct: 1 },
    { q: "أي من هذه الأجرام السماوية هو الأقرب للأرض؟", options: ["المريخ", "الشمس", "القمر", "الزهرة"], correct: 2 },
    { q: "أصغر وحدة بناء للمادة هي:", options: ["الجزيء", "المركب", "العنصر", "الذرة"], correct: 3 },
    { q: "من مكتشف الجاذبية الأرضية؟", options: ["أينشتاين", "نيوتن", "جاليليو", "طوماس إديسون"], correct: 1 },
    { q: "سرعة الضوء في الفراغ تقريبًا:", options: ["300,000 كم/ث", "150,000 كم/ث", "3,000 كم/ث", "1,000,000 كم/ث"], correct: 0 },
    { q: "المركب الأساسي في الغاز الطبيعي هو:", options: ["الميثان", "البروبان", "البوتان", "الإيثان"], correct: 0 },
    { q: "أي فصيلة دم تُعرف بالمانح العام؟", options: ["A", "B", "AB", "O"], correct: 3 },
    { q: "ما الغاز الذي تخرجه النباتات ليلًا؟", options: ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيليوم"], correct: 1 },
    { q: "أقرب كوكب للشمس هو:", options: ["عطارد", "الزهرة", "الأرض", "المريخ"], correct: 0 },
    { q: "عنصر مشع يستخدم في محطات الطاقة النووية:", options: ["الرصاص", "اليورانيوم", "الذهب", "الكربون"], correct: 1 },
    { q: "الطاقة الكامنة تتحول أثناء السقوط إلى طاقة...", options: ["حرارية", "كيميائية", "كهربائية", "حركية"], correct: 3 },
    { q: "ما المادة التي تشكل الجزء الأكبر من جسم الإنسان؟", options: ["البروتين", "العضلات", "الماء", "الدهون"], correct: 2 },
    { q: "ماذا يسمى تحول المادة من الحالة الصلبة إلى الغازية مباشرة؟", options: ["التكثف", "التسامي", "التبخر", "الانصهار"], correct: 1 },
    { q: "أي من التالي هو حمض؟", options: ["هيدروكسيد الصوديوم", "الأمونيا", "حمض الهيدروكلوريك", "الماء النقي"], correct: 2 },
    { q: "القوة التي تعيق حركة الأجسام عند تلامسها تسمى:", options: ["الجاذبية", "القصور", "الاحتكاك", "الدفع"], correct: 2 },
    { q: "العضو المسؤول عن ضخ الدم في جسم الإنسان:", options: ["القلب", "الرئة", "الكبد", "المخ"], correct: 0 },
    { q: "الوحدة المعيارية لقياس القوة هي:", options: ["الجول", "النيوتن", "الواط", "الفولت"], correct: 1 },
    { q: "أي الموجات التالية تحتاج إلى وسط ناقل؟", options: ["الضوء", "الراديو", "الصوت", "الأشعة السينية"], correct: 2 },
    { q: "ماذا يحدث للكثافة عند تسخين الغاز في وعاء مفتوح؟", options: ["تزيد", "تقل", "تبقى ثابتة", "تتلاشى"], correct: 1 },
    { q: "من الأمثلة على الطاقة المتجددة:", options: ["البترول", "الغاز الطبيعي", "الطاقة الشمسية", "الفحم"], correct: 2 },
    { q: "تستمد الأرض حرارتها بشكل رئيسي من:", options: ["القمر", "النجوم", "احتكاك الرياح", "الشمس"], correct: 3 },
    { q: "أي الفلزات التالية هو سائل في درجة حرارة الغرفة؟", options: ["الحديد", "الزئبق", "الصوديوم", "النحاس"], correct: 1 },
    { q: "الجزء المسؤول عن نقل الصفات الوراثية:", options: ["الميتوكوندريا", "الرايبوسوم", "DNA", "الغشاء البلازمي"], correct: 2 },
    { q: "نظائر العنصر الواحد تتشابه في...", options: ["العدد الكتلي", "عدد النيوترونات", "العدد الذري", "لا شيء مما سبق"], correct: 2 }
  ],
  math: [
    { q: "ما نتيجة: 5 * 6 + 4؟", options: ["50", "34", "54", "30"], correct: 1 },
    { q: "ما هو الجذر التربيعي لـ 144؟", options: ["10", "12", "14", "16"], correct: 1 },
    { q: "مثلث أطوال أضلاعه 3، 4 و5، ما نوع هذا المثلث؟", options: ["متساوي الأضلاع", "متساوي الساقين", "قائم الزاوية", "منفرج الزاوية"], correct: 2 },
    { q: "حل المعادلة: س + 7 = 15", options: ["6", "7", "8", "9"], correct: 2 },
    { q: "إذا كان س = 3، فإن قيمة (س^2 - 1) هي:", options: ["6", "8", "10", "12"], correct: 1 },
    { q: "مجموع زوايا المثلث الداخلية يساوي:", options: ["90", "180", "360", "270"], correct: 1 },
    { q: "مساحة مستطيل طوله 5 وعرضه 3 تساوي:", options: ["8", "15", "16", "20"], correct: 1 },
    { q: "خمسة أثمان (5/8) كسر عشري هو تقريباً:", options: ["0.5", "0.625", "0.75", "0.85"], correct: 1 },
    { q: "العدد الأصغر بين: 0.1، 0.09، 0.11، 0.099", options: ["0.1", "0.11", "0.09", "0.099"], correct: 2 },
    { q: "كم مليغرام في الجرام؟", options: ["10", "100", "1000", "10000"], correct: 2 },
    { q: "في الدائرة، القطر يساوي...", options: ["نصف القطر", "ضعف نصف القطر", "مربع نصف القطر", "محيط الدائرة"], correct: 1 },
    { q: "إذا كان مقياس الرسم 1:100، وطول خط 5 سم، فإن طوله الأصلي:", options: ["5 متر", "50 متر", "0.5 متر", "500 متر"], correct: 0 },
    { q: "العدد الذي يقبل القسمة على 2 و 3 هو بالضرورة يقبل القسمة على:", options: ["4", "5", "6", "9"], correct: 2 },
    { q: "ربع العدد 100 هو:", options: ["15", "20", "25", "50"], correct: 2 },
    { q: "10% من 500 يساوي:", options: ["10", "50", "100", "500"], correct: 1 },
    { q: "س^2 = 81، فإن س يمكن أن تكون:", options: ["9 فقط", "-9 فقط", "9 أو -9", "8"], correct: 2 },
    { q: "حجم مكعب طول حرفه 2 سم:", options: ["4", "6", "8", "16"], correct: 2 },
    { q: "الزاويتان المتتامتان مجموعهما يساوي:", options: ["90", "180", "360", "45"], correct: 0 },
    { q: "ناتج (12 ÷ 4) + (3 × 2):", options: ["9", "12", "18", "6"], correct: 0 },
    { q: "إذا كان محيط المربع 40، فإن طول ضلعه:", options: ["8", "10", "20", "100"], correct: 1 },
    { q: "عدد أولي من بين التالي:", options: ["10", "15", "17", "21"], correct: 2 },
    { q: "العدد 0.25 يعادل في الكسور:", options: ["1/2", "1/4", "1/5", "3/4"], correct: 1 },
    { q: "ما هو المضاعف المشترك الأصغر للعددين 4 و 6؟", options: ["10", "12", "24", "48"], correct: 1 },
    { q: "أوجد القاسم المشترك الأكبر للعددين 18 و 24:", options: ["2", "4", "6", "8"], correct: 2 },
    { q: "إذا تضاعف طول نصف قطر الدائرة، فمساحتها تتضاعف بمقدار:", options: ["مرتين", "3 مرات", "4 مرات", "نصف مرة"], correct: 2 },
    { q: "كم ضلعاً في المسدس؟", options: ["4", "5", "6", "7"], correct: 2 },
    { q: "طول أضلاع متوازي المستطيلات مختلفة، فكم مجموع الأوجه؟", options: ["4", "6", "8", "12"], correct: 1 },
    { q: "ما هي قيمة (2^3)؟", options: ["4", "6", "8", "9"], correct: 2 },
    { q: "احسب متوسط الأعداد: 2, 4, 6, 8:", options: ["3", "4", "5", "6"], correct: 2 },
    { q: "كم يوماً في السنة الكبيسة؟", options: ["364", "365", "366", "367"], correct: 2 }
  ],
  english: [
    { q: "Choose the correct answer: I ___ to the store yesterday.", options: ["go", "goes", "going", "went"], correct: 3 },
    { q: "What is the plural of 'child'?", options: ["childs", "children", "childrens", "child"], correct: 1 },
    { q: "Which word is an adjective?", options: ["Run", "Quickly", "Beautiful", "He"], correct: 2 },
    { q: "Identify the synonym for 'Happy'.", options: ["Sad", "Joyful", "Angry", "Tired"], correct: 1 },
    { q: "Choose the right spelling:", options: ["Nesesary", "Necessery", "Necessary", "Necesary"], correct: 2 },
    { q: "Fill in the blank: She has been living here ___ 2010.", options: ["since", "for", "in", "at"], correct: 0 },
    { q: "What is the opposite of 'Strong'?", options: ["Weak", "Tall", "Heavy", "Fast"], correct: 0 },
    { q: "Correct the sentence: He don't like apples.", options: ["He does no like", "He doesn't likes", "He doesn't like", "He not like"], correct: 2 },
    { q: "Can you tell me where ___?", options: ["is the station", "the station is", "is station", "station is"], correct: 1 },
    { q: "Which of the following is a verb?", options: ["Dog", "Blue", "Jump", "Soft"], correct: 2 },
    { q: "They ___ playing football now.", options: ["is", "are", "have", "do"], correct: 1 },
    { q: "Choose the correct article: I saw ___ elephant at the zoo.", options: ["a", "an", "the", "no article"], correct: 1 },
    { q: "What does 'brilliant' mean?", options: ["Very dark", "Very smart/bright", "Very heavy", "Very tall"], correct: 1 },
    { q: "If I ___ you, I would study harder.", options: ["was", "am", "were", "be"], correct: 2 },
    { q: "The book is ___ the table.", options: ["in", "on", "at", "by"], correct: 1 },
    { q: "Which word rhymes with 'night'?", options: ["Kite", "Knit", "Neat", "Note"], correct: 0 },
    { q: "A person who designs buildings is an ___.", options: ["Doctor", "Teacher", "Architect", "Actor"], correct: 2 },
    { q: "Water ___ at 100 degrees Celsius.", options: ["boils", "boiling", "boil", "boiled"], correct: 0 },
    { q: "I have ___ friends in this city.", options: ["much", "many", "any", "little"], correct: 1 },
    { q: "She loves reading, ___ she?", options: ["doesn't", "don't", "isn't", "hasn't"], correct: 0 },
    { q: "What is the past participle of 'write'?", options: ["Wrote", "Written", "Writing", "Write"], correct: 1 },
    { q: "Choose the antonym for 'Expand':", options: ["Grow", "Widen", "Shrink", "Open"], correct: 2 },
    { q: "We are going to Paris ___ the weekend.", options: ["in", "on", "at", "by"], correct: 2 }, // or on
    { q: "I'll call you as soon as I ___ .", options: ["will arrive", "arriving", "arrive", "arrived"], correct: 2 },
    { q: "He is taller ___ his brother.", options: ["then", "than", "from", "to"], correct: 1 },
    { q: "Select the correct pronoun: Every student must bring ___ own book.", options: ["their", "his/her", "there", "they"], correct: 1 }, // traditionally "his/her" or "their" in modern, but let's accept "his/her" or "their". "their" is safer. Let's make it unambiguous.
    { q: "What time ___ you wake up today?", options: ["do", "did", "are", "have"], correct: 1 },
    { q: "The car needs ___ .", options: ["to washing", "washing", "washed", "wash"], correct: 1 },
    { q: "It's the ___ movie I've ever seen.", options: ["better", "good", "best", "most good"], correct: 2 },
    { q: "I look forward to ___ you.", options: ["see", "seeing", "saw", "seen"], correct: 1 }
  ]
};
